Fix compatibility with `ruby-3.1` by adding bundled gems
Since this ruby release `net-imap` and `net-smtp`
are not required by default

See ruby changelog [here](https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/)
This fix errors like this:
```
LoadError: cannot load such file -- net/imap
/home/user/.rvm/gems/ruby-3.1.0/gems/gmail-0.7.1/lib/gmail.rb:1:in `require'
/home/user/.rvm/gems/ruby-3.1.0/gems/gmail-0.7.1/lib/gmail.rb:1:in `<top (required)>'

```